### ISSUE TITLE
data collection

### ISSUE THREAD

**Issue by April2th21** [facebookresearch/3D-Vision-and-Touch#2]
Hello, 
I'm very interested in your work. Could you provide the following code for collecting data?

**Comment by EdwardSmith1884** [comment]
Hi, we will be releasing a simulator which allows you to do this in the next week or two. I will link here when it becomes available. For now though all of the data is available for download if you need it.

**Comment by lxiaol21** [comment]
Hello, have you updated the link of data collection?

thank you

**Comment by EdwardSmith1884** [comment]
Here it is and sorry for the delay: https://github.com/facebookresearch/Active-3D-Vision-and-Touch
