### ISSUE TITLE
how to use the dataset?

### ISSUE THREAD

**Issue by sinjutin** [facebookresearch/3D-Vision-and-Touch#3]
Excuse me, I'd like to know how to use the ABC dataset for trainning? I don't know what the exp_type and exp_id is?the name of the directory?

**Comment by sinjutin** [comment]
> Excuse me, I'd like to know how to use the ABC dataset for trainning? I don't know what the exp_type and exp_id is?the name of the directory?

I have made it, sorry to interrupt.

**Comment by EdwardSmith1884** [comment]
everything is clear then? do you need any other help?

**Comment by sinjutin** [comment]
> everything is clear then? do you need any other help?

No, thank you.
